services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=notification_db'
      - 'POSTGRES_PASSWORD=ensalada123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
