version: '3.8'

services:
  # NGINX API Gateway
  nginx-gateway:
    image: nginx:1.25-alpine
    container_name: batistella-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx-gateway/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx-gateway/conf/gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ../nginx-gateway/html:/usr/share/nginx/html:ro
      - ../nginx-gateway/logs:/var/log/nginx
      - ../nginx-gateway/ssl:/etc/nginx/ssl:ro
    depends_on:
      - auth-service
      - user-service
      - api-service
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio de Autenticación
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    container_name: batistella-auth
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres-auth:5432/auth_db
      - DATABASE_USERNAME=auth_user
      - DATABASE_PASSWORD=auth_password
      - JWT_SECRET=batistella-jwt-secret-key-2024
      - JWT_EXPIRATION=86400000
    depends_on:
      - postgres-auth
      - redis
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio de Usuarios
  user-service:
    build:
      context: ../services/user-service
      dockerfile: Dockerfile
    container_name: batistella-users
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres-users:5432/users_db
      - DATABASE_USERNAME=users_user
      - DATABASE_PASSWORD=users_password
    depends_on:
      - postgres-users
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio API Principal
  api-service:
    build:
      context: ../services/api-service
      dockerfile: Dockerfile
    container_name: batistella-api
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres-api:5432/api_db
      - DATABASE_USERNAME=api_user
      - DATABASE_PASSWORD=api_password
    depends_on:
      - postgres-api
    networks:
      - batistella-network
    restart: unless-stopped

  # Base de datos para Auth Service
  postgres-auth:
    image: postgres:15-alpine
    container_name: batistella-postgres-auth
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ../gateway-config/security/init-auth.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - batistella-network
    restart: unless-stopped

  # Base de datos para User Service
  postgres-users:
    image: postgres:15-alpine
    container_name: batistella-postgres-users
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=users_user
      - POSTGRES_PASSWORD=users_password
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    networks:
      - batistella-network
    restart: unless-stopped

  # Base de datos para API Service
  postgres-api:
    image: postgres:15-alpine
    container_name: batistella-postgres-api
    environment:
      - POSTGRES_DB=api_db
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=api_password
    volumes:
      - postgres_api_data:/var/lib/postgresql/data
    networks:
      - batistella-network
    restart: unless-stopped

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: batistella-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - batistella-network
    restart: unless-stopped

  # Herramienta de administración de BD
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: batistella-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@batistella.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - batistella-network
    restart: unless-stopped

volumes:
  postgres_auth_data:
  postgres_users_data:
  postgres_api_data:
  redis_data:
  pgadmin_data:

networks:
  batistella-network:
    driver: bridge 