services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: batistella-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ensalada123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
    networks:
      - batistella-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NGINX API Gateway
  nginx-gateway:
    image: nginx:1.25-alpine
    container_name: batistella-gateway
    ports:
      - "80:80"
    volumes:
      - ./Bati/nginx-gateway/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Bati/nginx-gateway/conf/gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Bati/nginx-gateway/html:/usr/share/nginx/html:ro
      - ./Bati/nginx-gateway/logs:/var/log/nginx
    depends_on:
      - frontend
      - usersandlogin
      - productsandorder
      - payments
      - notifications
      - dashboards
    networks:
      - batistella-network
    restart: unless-stopped

  # Frontend Angular
  frontend:
    build:
      context: ./FrontEnd/BatistellaFront
      dockerfile: Dockerfile.prod
    container_name: batistella-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      - API_URL=https://batistellaycia.shop
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio de Usuarios y Login
  usersandlogin:
    build:
      context: ./UsersAndLogin
      dockerfile: Dockerfile
    container_name: batistella-usersandlogin
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/UsersBatistella_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ensalada123
      - JWT_SECRET=NmQ4YzJhMjEtZjc2NC00MTM3LWI2ZTgtNDJiMmZiNjM5YzBk
      - JWT_EXPIRATION=86400000
      - NOTIFICATION_SERVICE_URL=http://notifications:8080
      - APP_BASE_URL=https://www.batistellaycia.shop
      - APP_FRONTEND_URL=https://www.batistellaycia.shop
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio de Productos y Órdenes
  productsandorder:
    build:
      context: ./ProductsAndOrder
      dockerfile: Dockerfile
    container_name: batistella-productsandorder
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ProductsAndOrders
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ensalada123
      - MICROSERVICE_USUARIOS_URL=http://usersandlogin:8080/api/users
      - MICROSERVICE_PAYMENT_URL=http://payments:8084/api/pagos/estado/{codigoPedido}
      - JWT_SECRET=NmQ4YzJhMjEtZjc2NC00MTM3LWI2ZTgtNDJiMmZiNjM5YzBk
      - APP_BASE_URL=https://www.batistellaycia.shop
      - GATEWAY_URL=https://www.batistellaycia.shop
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio de Pagos
  payments:
    build:
      context: ./Payments
      dockerfile: Dockerfile
    container_name: batistella-payments
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Payments
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ensalada123
      - JWT_SECRET=NmQ4YzJhMjEtZjc2NC00MTM3LWI2ZTgtNDJiMmZiNjM5YzBk
      - APP_BASE_URL=https://www.batistellaycia.shop
      - APP_FRONTEND_URL=https://www.batistellaycia.shop
      - MERCADOPAGO_ACCESS_TOKEN=APP_USR-4153672979949236-052121-b15239becd36997a08cb0fba8c64183e-2454389820
      - MERCADOPAGO_PUBLIC_KEY=APP_USR-d9e97257-5ded-498d-a4e8-cfa715ab9814
      - PAYMENT_SERVICE_URL=https://www.batistellaycia.shop/api/payments/estado
      - MICROSERVICE_NOTIFICATIONS_URL=http://notifications:8085
      - MICROSERVICE_PEDIDOS_URL=http://productsandorder:8083
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio de Notificaciones
  notifications:
    build:
      context: ./Notifications
      dockerfile: Dockerfile
    container_name: batistella-notifications
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ensalada123
      - JWT_SECRET=NmQ4YzJhMjEtZjc2NC00MTM3LWI2ZTgtNDJiMmZiNjM5YzBk
      - APP_BASE_URL=https://www.batistellaycia.shop
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - batistella-network
    restart: unless-stopped

  # Servicio de Dashboards
  dashboards:
    build:
      context: ./Dashboards
      dockerfile: Dockerfile
    container_name: batistella-dashboards
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8086
      - JWT_SECRET=NmQ4YzJhMjEtZjc2NC00MTM3LWI2ZTgtNDJiMmZiNjM5YzBk
      - JWT_EXPIRATION=86400000
      - APP_BASE_URL=https://www.batistellaycia.shop
      - APP_FRONTEND_URL=https://www.batistellaycia.shop
      - ALLOWED_ORIGINS=http://localhost:4200,https://www.batistellaycia.shop
      # URLs de microservicios que consume
      - USERS_SERVICE_URL=http://usersandlogin:8080
      - PRODUCTS_SERVICE_URL=http://productsandorder:8083
      - PAYMENTS_SERVICE_URL=http://payments:8084
      - NOTIFICATIONS_SERVICE_URL=http://notifications:8085
    depends_on:
      - usersandlogin
      - productsandorder
      - payments
      - notifications
    networks:
      - batistella-network
    restart: unless-stopped

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: batistella-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - batistella-network
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:

networks:
  batistella-network:
    driver: bridge 