version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
      - APP_BASE_URL=${APP_BASE_URL}
      - APP_FRONTEND_URL=${APP_FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
      - MERCADOPAGO_PUBLIC_KEY=${MERCADOPAGO_PUBLIC_KEY}
      - MICROSERVICE_NOTIFICATIONS_URL=${NOTIFICATIONS_SERVICE_URL}
      - MICROSERVICE_PEDIDOS_URL=${PEDIDOS_SERVICE_URL}
    networks:
      - batistella-network
    restart: always
    env_file:
      - .env

networks:
  batistella-network:
    name: batistella-network
    external: true
