-- Inserción de marcas
INSERT INTO marca (nombre) VALUES ('TopNutrition') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Kenl') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Odwalla') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('9Lives') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Amici') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Zimpi') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('ProPlan') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Ganacat') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Ganacan') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Compinches') ON CONFLICT DO NOTHING;
INSERT INTO marca (nombre) VALUES ('Exact') ON CONFLICT DO NOTHING;


