version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/UsersBatistella_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ensalada123
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=UsersBatistella_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ensalada123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: 